typography_spectrum: 0.52182
color:
  brandColors:
    - '#121212'
    - '#ffffff'
    - '#636060'
    - '#f64e5d'
    - '#3bb7e8'
  brandStrength: 0.9762775609269738
  lightness: 0.45710190245881677
  saturation: 0.7195432796142995
  rhythmicContrast: 0.06621566275134683
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75703
analytics:
  google: null
  facebook: null
  twitter: null
name: eloythesaint
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Eloy the Saint
description: RPG Writer and Designer
purpose: []
